CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(255) UNIQUE,
    agency_name VARCHAR(255),
    license_number VARCHAR(255),
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_agents_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE buyer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(255),
    preferred_city VARCHAR(255),
    budget_min DOUBLE PRECISION,
    budget_max DOUBLE PRECISION,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_buyer_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE listing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(2000),
    address VARCHAR(255),
    city VARCHAR(255),
    price DOUBLE PRECISION,
    bedrooms INTEGER,
    image VARCHAR(255),
    bathrooms INTEGER,
    area DOUBLE PRECISION,
    property_type VARCHAR(255),
    listing_status VARCHAR(255),
    agent_id BIGINT,
    CONSTRAINT fk_listing_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
);

CREATE TABLE buyer_requested_listings (
    buyer_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    PRIMARY KEY (buyer_id, listing_id),
    CONSTRAINT fk_buyer_requested_buyer FOREIGN KEY (buyer_id) REFERENCES buyer (id),
    CONSTRAINT fk_buyer_requested_listing FOREIGN KEY (listing_id) REFERENCES listing (id)
);

CREATE TABLE agent_requested_listings (
    agent_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    PRIMARY KEY (agent_id, listing_id),
    CONSTRAINT fk_agent_requested_agent FOREIGN KEY (agent_id) REFERENCES agents (id),
    CONSTRAINT fk_agent_requested_listing FOREIGN KEY (listing_id) REFERENCES listing (id)
);

CREATE INDEX idx_listing_city ON listing (city);
CREATE INDEX idx_listing_agent_id ON listing (agent_id);
CREATE INDEX idx_buyer_requested_listing_id ON buyer_requested_listings (listing_id);
CREATE INDEX idx_agent_requested_listing_id ON agent_requested_listings (listing_id);
